# Generated by Django 5.0.1 on 2026-01-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_alter_lessonprogress_watched_seconds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="duration_hours",
            field=models.FloatField(),
        ),
    ]
